### Admin login
POST https://capstone-project-1fpf.onrender.com
Content-Type: application/json

{
  "email":"admin@mail.com",
  "password":"admin"
}

### Read all USERS & AUTHORS (email)

### Block or Activate User or Author