### Register User
POST https://capstone-project-1fpf.onrender.com/auth/users
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "email": "user112377@mail.com",
  "role":"USER",
  "password": "",
  "profileImageUrl": "https://example.com/avatars/user.png"
}

### User Login
POST https://capstone-project-1fpf.onrender.com/auth/login
Content-Type: application/json

{
  "email":"user1@mail.com",
  "password":"user1"
}

### User logout
GET https://capstone-project-1fpf.onrender.com/auth/logout


### Read articles of all authors
GET https://capstone-project-1fpf.onrender.com/user-api/articles

### Add comment by user to an article
PUT https://capstone-project-1fpf.onrender.com/user-api/articles
Content-Type: application/json

{
  "articleId":"fdgdgdgdfgdfg",
  "comment":"This is useful article"
}



### Change password
PUT https://capstone-project-1fpf.onrender.com/auth/password
Content-Type: application/json

{
  "currentPassword":"",
  "newPassword":""
}